# Generated by Django 5.2.9 on 2025-12-31 23:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('year', models.CharField(help_text='مثال: ۱۴۰۳-۱۴۰۴', max_length=9, unique=True, verbose_name='سال تحصیلی')),
                ('is_default', models.BooleanField(default=False, help_text='فقط یک سال می\u200cتواند پیش\u200cفرض باشد', verbose_name='سال پیش\u200cفرض')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'سال تحصیلی',
                'verbose_name_plural': 'سال\u200cهای تحصیلی',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('name', models.CharField(max_length=200, verbose_name='نام مدرسه')),
                ('gender', models.CharField(choices=[('M', 'پسرانه'), ('F', 'دخترانه')], max_length=1, verbose_name='جنسیت')),
                ('level', models.CharField(choices=[('PRIMARY', 'ابتدایی (۱ تا ۶)'), ('MIDDLE', 'متوسطه اول (۷ تا ۹)'), ('HIGH', 'متوسطه دوم (۱۰ تا ۱۲)')], max_length=10, verbose_name='مقطع تحصیلی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس مدرسه')),
                ('education_manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مسئول آموزش')),
                ('manager_phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل باید با ۰۹ شروع شود و ۱۱ رقم باشد.')], verbose_name='موبایل مسئول آموزش')),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر وارد کنید')], verbose_name='ایمیل مسئول آموزش')),
                ('fabric_color_image', models.ImageField(blank=True, null=True, upload_to='schools/fabric/', verbose_name='عکس نمونه پارچه')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد')),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدارس',
                'unique_together': {('name', 'gender', 'level')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='پایه تحصیلی')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='شعبه (مثلاً الف، ب)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicyear', verbose_name='سال تحصیلی')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='core.school', verbose_name='مدرسه')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['grade'],
                'unique_together': {('school', 'grade', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید دقیقاً ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره موبایل باید با ۰۹ شروع شود و ۱۱ رقم باشد.')], verbose_name='شماره موبایل')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.classroom', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('class_room', 'national_id')},
            },
        ),
    ]
