# Generated by Django 5.2.9 on 2025-12-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد'),
        ),
    ]
