# Generated by Django 5.2.9 on 2026-02-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='education_manager',
            field=models.CharField(default=1, max_length=100, verbose_name='نام مسئول آموزش'),
            preserve_default=False,
        ),
    ]
