# Generated by Django 5.2.9 on 2025-12-24 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_contract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='ایمیل معتبر وارد کنید')], verbose_name='ایمیل مسئول آموزش'),
        ),
    ]
