# Generated by Django 5.2.9 on 2026-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_school_education_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='سال پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=9, unique=True, verbose_name='سال تحصیلی'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_academic_year'),
        ),
    ]
