# Generated by Django 5.2.9 on 2025-12-31 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('gender', models.CharField(choices=[('M', 'پسرانه'), ('F', 'دخترانه')], max_length=1, verbose_name='جنسیت لباس')),
                ('type', models.CharField(choices=[('SHIRT', 'پیراهن'), ('PANTS', 'شلوار'), ('MANTOO', 'مانتو'), ('MAGHNAEH', 'مقنعه')], max_length=10, verbose_name='نوع لباس')),
            ],
            options={
                'verbose_name': 'نوع لباس',
                'verbose_name_plural': 'انواع لباس',
                'unique_together': {('gender', 'type')},
            },
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('size', models.CharField(max_length=10, verbose_name='سایز')),
                ('clothing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='uniforms.clothingtype', verbose_name='نوع لباس')),
            ],
            options={
                'verbose_name': 'سایز لباس',
                'verbose_name_plural': 'سایزهای لباس',
                'ordering': ['clothing_type', 'size'],
                'unique_together': {('clothing_type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='AgreedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agreed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ توافقی کل')),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ علی\u200cالحساب')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.academicyear', verbose_name='سال تحصیلی')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreed_prices', to='core.school', verbose_name='مدرسه')),
                ('clothing_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='uniforms.clothingsize', verbose_name='سایز لباس')),
            ],
            options={
                'verbose_name': 'قیمت توافقی',
                'verbose_name_plural': 'قیمت\u200cهای توافقی',
                'unique_together': {('academic_year', 'school', 'clothing_size')},
            },
        ),
    ]
