# Generated by Django 5.2.9 on 2025-12-13 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaghnaehSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('size', models.CharField(choices=[('1', 'سایز ۱'), ('2', 'سایز ۲'), ('3', 'سایز ۳'), ('4', 'سایز ۴'), ('5', 'سایز ۵'), ('90', '۹۰'), ('100', '۱۰۰')], max_length=10, unique=True, verbose_name='سایز مقنعه')),
            ],
            options={
                'verbose_name': 'سایز مقنعه',
                'verbose_name_plural': 'سایزهای مقنعه',
            },
        ),
        migrations.CreateModel(
            name='MantooSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('size', models.CharField(choices=[('22', '۲۲'), ('24', '۲۴'), ('26', '۲۶'), ('28', '۲۸'), ('30', '۳۰'), ('32', '۳۲'), ('34', '۳۴'), ('36', '۳۶'), ('38', '۳۸'), ('40', '۴۰'), ('42', '۴۲'), ('44', '۴۴'), ('46', '۴۶'), ('48', '۴۸'), ('50', '۵۰')], max_length=10, unique=True, verbose_name='سایز مانتو')),
            ],
            options={
                'verbose_name': 'سایز مانتو',
                'verbose_name_plural': 'سایزهای مانتو',
            },
        ),
        migrations.CreateModel(
            name='PantsSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('size', models.CharField(choices=[('36', '۳۶'), ('38', '۳۸'), ('40', '۴۰'), ('42', '۴۲'), ('44', '۴۴'), ('46', '۴۶'), ('48', '۴۸'), ('50', '۵۰'), ('52', '۵۲'), ('54', '۵۴'), ('56', '۵۶'), ('58', '۵۸'), ('100', '۱۰۰'), ('105', '۱۰۵')], max_length=10, unique=True, verbose_name='سایز شلوار')),
            ],
            options={
                'verbose_name': 'سایز شلوار',
                'verbose_name_plural': 'سایزهای شلوار',
            },
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('size', models.CharField(choices=[('S', 'اسمال'), ('M', 'مدیوم'), ('L', 'لارج'), ('XL', 'اکسترا لارج'), ('2XL', '۲ اکسترا لارج'), ('3XL', '۳ اکسترا لارج'), ('4XL', '۴ اکسترا لارج'), ('5XL', '۵ اکسترا لارج'), ('6XL', '۶ اکسترا لارج')], max_length=10, unique=True, verbose_name='سایز پیراهن')),
            ],
            options={
                'verbose_name': 'سایز پیراهن',
                'verbose_name_plural': 'سایزهای پیراهن',
            },
        ),
        migrations.CreateModel(
            name='StudentSelectionBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('pants_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boy_selections', to='uniforms.pantssize', verbose_name='سایز شلوار انتخابی')),
                ('shirt_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boy_selections', to='uniforms.shirtsize', verbose_name='سایز پیراهن انتخابی')),
                ('student', models.OneToOneField(limit_choices_to={'class_room__school__gender': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='boy_selection', to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'انتخاب سایز پسرانه',
                'verbose_name_plural': 'انتخاب\u200cهای سایز پسرانه',
            },
        ),
        migrations.CreateModel(
            name='StudentSelectionGirl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('maghnaeh_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='girl_selections', to='uniforms.maghnaehsize', verbose_name='سایز مقنعه انتخابی')),
                ('mantoo_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='girl_selections', to='uniforms.mantoosize', verbose_name='سایز مانتو انتخابی')),
                ('student', models.OneToOneField(limit_choices_to={'class_room__school__gender': 'F'}, on_delete=django.db.models.deletion.PROTECT, related_name='girl_selection', to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'انتخاب سایز دخترانه',
                'verbose_name_plural': 'انتخاب\u200cهای سایز دخترانه',
            },
        ),
        migrations.CreateModel(
            name='AgreedMaghnaehPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agreed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ توافقی کل')),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ علی\u200cالحساب')),
                ('school', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.PROTECT, related_name='maghnaeh_prices', to='core.school', verbose_name='مدرسه')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='uniforms.maghnaehsize', verbose_name='سایز مقنعه')),
            ],
            options={
                'verbose_name': 'قیمت توافقی مقنعه',
                'verbose_name_plural': 'قیمت\u200cهای توافقی مقنعه',
                'unique_together': {('school', 'size')},
            },
        ),
        migrations.CreateModel(
            name='AgreedMantooPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agreed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ توافقی کل')),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ علی\u200cالحساب')),
                ('school', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.PROTECT, related_name='mantoo_prices', to='core.school', verbose_name='مدرسه')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='uniforms.mantoosize', verbose_name='سایز مانتو')),
            ],
            options={
                'verbose_name': 'قیمت توافقی مانتو',
                'verbose_name_plural': 'قیمت\u200cهای توافقی مانتو',
                'unique_together': {('school', 'size')},
            },
        ),
        migrations.CreateModel(
            name='AgreedPantsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agreed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ توافقی کل')),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ علی\u200cالحساب')),
                ('school', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='pants_prices', to='core.school', verbose_name='مدرسه')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='uniforms.pantssize', verbose_name='سایز شلوار')),
            ],
            options={
                'verbose_name': 'قیمت توافقی شلوار',
                'verbose_name_plural': 'قیمت\u200cهای توافقی شلوار',
                'unique_together': {('school', 'size')},
            },
        ),
        migrations.CreateModel(
            name='AgreedShirtPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('agreed_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ توافقی کل')),
                ('advance_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ علی\u200cالحساب')),
                ('school', models.ForeignKey(limit_choices_to={'gender': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='shirt_prices', to='core.school', verbose_name='مدرسه')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='uniforms.shirtsize', verbose_name='سایز پیراهن')),
            ],
            options={
                'verbose_name': 'قیمت توافقی پیراهن',
                'verbose_name_plural': 'قیمت\u200cهای توافقی پیراهن',
                'unique_together': {('school', 'size')},
            },
        ),
    ]
