# Generated by Django 5.2.9 on 2025-12-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('uniforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'علی\u200cالحساب'), ('FINAL', 'تسویه نهایی'), ('EXTRA', 'پرداخت اضافی'), ('REFUND', 'استرداد')], default='ADVANCE', max_length=10, verbose_name='نوع پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=10, verbose_name='وضعیت')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری درگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_ready1', models.BooleanField(default=False, verbose_name='لباس اصلی آماده؟')),
                ('is_ready2', models.BooleanField(default=False, verbose_name='لباس فرعی آماده؟')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تسویه کامل شده؟')),
                ('clothing_size1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selections_as_primary', to='uniforms.clothingsize', verbose_name='سایز لباس اصلی (پیراهن/مانتو)')),
                ('clothing_size2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selections_as_secondary', to='uniforms.clothingsize', verbose_name='سایز لباس فرعی (شلوار/مقنعه)')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='selection', to='core.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'انتخاب سایز دانش\u200cآموز',
                'verbose_name_plural': 'انتخاب\u200cهای سایز دانش\u200cآموزان',
            },
        ),
    ]
